all : memory1.o memory2.o memory3.o memory4.o memory5a.o memory5b.o memory6.o

memory1.o : memory1.c
	cc memory1.c -o memory1.o
memory2.o : memory2.c
	cc memory2.c -o memory2.o
memory3.o : memory3.c
	cc memory3.c -o memory3.o
memory4.o : memory4.c
	cc memory4.c -o memory4.o
memory5a.o : memory5a.c
	cc memory5a.c -o memory5a.o
memory5b.o : memory5b.c
	cc memory5b.c -o memory5b.o
memory6.o : memory6.c
	cc memory6.c -o memory6.o

clean :
	rm memory1.o memory2.o memory3.o memory4.o memory5a.o memory5b.o memory6.o
